name: CI

on: [pull_request, push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 16
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm release
      - name: Update lockfile
        run: pnpm install
      - name: Commit lockfile
        run: |
          git config --global user.name 'Jan Müller [bot]'
          git config --global user.email 'janmueller3698@gmail.com
          git commit -am "Update lockfile"
          git push
